### ISSUE TITLE
Bet ticker sometimes needs manual refresh

### ISSUE THREAD

**Issue by SimBuckeye** [c-o-l-i-n/joshies#67]
Reproduce:
- Have a full ticker
- Resolve all bets (empty ticker)
- Place more bets

The height adjusts to the new bets but the bets themselves are not displayed

**Comment by VoxelPenguin** [comment]
Upon further investigation, the issue occurred when the total number of active bets decreased to below the number of bets visible on the carousel (in this case, from 6 to 5).  This was fixed by showing a static list of bets when the total number of active bets is less than the number of visible bets, and showing the carousel when there are more active bets than carousel slots.
